[package]
name = "rust-leetcode"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.14.0"
literally = "0.1.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
test-case = "3.3.1"
